Fix errors in templates

diff --git a/gui/res/discover_wakeup.tmpl b/gui/res/discover_wakeup.tmpl
--- a/gui/res/discover_wakeup.tmpl
+++ b/gui/res/discover_wakeup.tmpl
@@ -1,39 +1,39 @@
 SECONDS=0
-	# Wait for console to be in sleep/rest mode or on (otherwise console isn't available)
-	ps_status="$(flatpak run io.github.streetpea.Chiaki4deck discover -h ${addr} 2>/dev/null)"
-	while ! echo "${ps_status}" | grep -q 'ready\|standby'
-	do
-	    if [ ${SECONDS} -gt{{wait_timeout}} ]
-	    then
-	        if [ "${local}" = true ]
-	        then
-	            connect_error_loc
-	        else
-	            connect_error_ext
-	        fi
-	    fi
-	    sleep 1
-	    ps_status="$(flatpak run io.github.streetpea.Chiaki4deck discover -h ${addr} 2>/dev/null)"
-	done
-
-	# Wake up console from sleep/rest mode if not already awake
-	if ! echo "${ps_status}" | grep -q ready
+# Wait for console to be in sleep/rest mode or on (otherwise console isn't available)
+ps_status="$(flatpak run io.github.streetpea.Chiaki4deck discover -h ${addr} 2>/dev/null)"
+while ! echo "${ps_status}" | grep -q 'ready\|standby'
+do
+	if [ ${SECONDS} -gt {{wait_timeout}} ]
 	then
-	    flatpak run io.github.streetpea.Chiaki4deck wakeup {{ps_console}} -h ${addr} -r '{{regist_key}}' 2>/dev/null
+		if [ "${local}" = true ]
+		then
+			connect_error_loc
+		else
+			connect_error_ext
+		fi
 	fi
+	sleep 1
+	ps_status="$(flatpak run io.github.streetpea.Chiaki4deck discover -h ${addr} 2>/dev/null)"
+done
 
-	# Wait for PlayStation to report ready status, exit script on error if it never happens.
-	while ! echo "${ps_status}" | grep -q ready
-	do
-	    if [ ${SECONDS} -gt{{wait_timeout}} ]
-	    then
-	        if echo "${ps_status}" | grep -q standby
-	        then
-	            wakeup_error
-	        else
-	            timeout_error
-	        fi
-	    fi
-	    sleep 1
-	    ps_status="$(flatpak run io.github.streetpea.Chiaki4deck discover -h ${addr} 2>/dev/null)"
-	done
+# Wake up console from sleep/rest mode if not already awake
+if ! echo "${ps_status}" | grep -q ready
+then
+	flatpak run io.github.streetpea.Chiaki4deck wakeup -{{ps_console}} -h ${addr} -r '{{regist_key}}' 2>/dev/null
+fi
+
+# Wait for PlayStation to report ready status, exit script on error if it never happens.
+while ! echo "${ps_status}" | grep -q ready
+do
+	if [ ${SECONDS} -gt {{wait_timeout}} ]
+	then
+		if echo "${ps_status}" | grep -q standby
+		then
+			wakeup_error
+		else
+			timeout_error
+		fi
+	fi
+	sleep 1
+	ps_status="$(flatpak run io.github.streetpea.Chiaki4deck discover -h ${addr} 2>/dev/null)"
+done
diff --git a/gui/res/shortcut.tmpl b/gui/res/shortcut.tmpl
--- a/gui/res/shortcut.tmpl
+++ b/gui/res/shortcut.tmpl
@@ -26,7 +26,7 @@ wakeup_error()
 
 timeout_error()
 {
-    echo "Error: PlayStation console didn't become ready in{{wait_timeout}} seconds!" >&2
-    echo "Error: Please change{{wait_timeout}} to a higher number in your script if this persists." >&2
+    echo "Error: PlayStation console didn't become ready in {{wait_timeout}} seconds!" >&2
+    echo "Error: Please change {{wait_timeout}} to a higher number in your script if this persists." >&2
     exit 1
 }
